trigger:
    branches:
        include:
            - '*'
    tags:
        include:
            - '*'

jobs:
    - job: Linux
      pool:
          vmImage: 'ubuntu-16.04'
      steps:
          - script: |
              curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
              echo '##vso[task.setvariable variable=PATH]$(PATH):$(HOME)/.cargo/bin'
            displayName: Install rustup

          - script: |
              cargo install cargo2junit
              rustup target add x86_64-unknown-linux-musl
              sudo apt-get -qq install musl-tools
            displayName: Install tools

          - script: |
              cargo test -- -Z unstable-options --format json | cargo2junit > results.xml
            displayName: Run test

          - task: PublishTestResults@2
            inputs:
                testResultsFormat: 'JUnit'
                testResultsFiles: 'results.xml'
            condition: succeededOrFailed()

          - script: |
              make release_lnx
              cp *.zip $(Build.ArtifactStagingDirectory)
            displayName: Build release binary

          - task: PublishBuildArtifacts@1
            inputs:
                artifactName: 'Linux'
                pathtoPublish: $(Build.ArtifactStagingDirectory)

    - job: macOS
      pool:
          vmImage: 'macos-10.13'
      steps:
          - script: |
              curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
              echo '##vso[task.setvariable variable=PATH]$(PATH):$(HOME)/.cargo/bin'
            displayName: Install rustup

          - script: |
              cargo install cargo2junit
            displayName: Install tools

          - script: |
              cargo test -- -Z unstable-options --format json | cargo2junit > results.xml
            displayName: Run test

          - task: PublishTestResults@2
            inputs:
                testResultsFormat: 'JUnit'
                testResultsFiles: 'results.xml'
            condition: succeededOrFailed()

          - script: |
              make release_mac
              cp *.zip $(Build.ArtifactStagingDirectory)
            displayName: Build release binary

          - task: PublishBuildArtifacts@1
            inputs:
                artifactName: 'macOS'
                pathtoPublish: $(Build.ArtifactStagingDirectory)

    - job: Windows
      pool:
          vmImage: 'vs2017-win2016'
      steps:
          - script: |
              curl -sSf -o rustup-init.exe https://win.rustup.rs
              rustup-init.exe -y --default-toolchain stable
              set PATH=%PATH%;%USERPROFILE%\.cargo\bin
              echo '##vso[task.setvariable variable=PATH]%PATH%'
            displayName: Install rustup

          - script: |
              choco install -y zip
              cargo install cargo2junit
            displayName: Install tools

          - script: |
              cargo test -- -Z unstable-options --format json | cargo2junit > results.xml
            displayName: Run test

          - task: PublishTestResults@2
            inputs:
                testResultsFormat: 'JUnit'
                testResultsFiles: 'results.xml'
            condition: succeededOrFailed()

          - script: |
              make release_win
              cp *.zip $(Build.ArtifactStagingDirectory)
            displayName: Build release binary

          - task: PublishBuildArtifacts@1
            inputs:
                artifactName: 'Windows'
                pathtoPublish: $(Build.ArtifactStagingDirectory)

    - job: Release
      dependsOn:
          - Linux
          - macOS
          - Windows
      steps:
          - task: DownloadBuildArtifacts@0
            inputs:
                downloadType: 'specific'
                itemPattern: '**'
                downloadPath: $(Build.ArtifactStagingDirectory)

          - script: ls $(Build.ArtifactStagingDirectory)

          - task: GitHubRelease@0
            inputs:
                gitHubConnection: 'dalance'
                repositoryName: 'dalance/procs'
                tagSource: 'auto'
                releaseNotesSource: 'input'
                releaseNotes: '[Changelog](https://github.com/dalance/procs/blob/master/CHANGELOG.md)'
                assets: '$(Build.ArtifactStagingDirectory)/*/*'
                assetUploadMode: 'replace'
                isDraft: false
                isPreRelease: false
                addChangeLog: false
            displayName: Release to GitHub
