[package]
name = "procs"
version = "0.1.1-pre"
authors = ["dalance@gmail.com"]
repository = "https://github.com/dalance/procs"
keywords = ["process"]
categories = ["command-line-utilities"]
license = "MIT"
readme = "README.md"
description = "A modern replacement for ps"
edition = "2018"

[features]
udp = []

[dependencies]
console     = "0.7.5"
chrono      = "0.4.6"
failure     = "0.1.5"
lazy_static = "1.2.0"
procfs      = "0.4.2"
users       = "0.8.1"
structopt   = "0.2.14"
unbytify    = "0.2.0"

#[patch.crates-io]
#procfs = { git = "https://github.com/dalance/procfs", branch = "add_udp" }

[package.metadata.release]
dev-version-ext            = "pre"
pre-release-commit-message = "Prepare to v{{version}}"
pro-release-commit-message = "Start next development iteration v{{version}}"
tag-message                = "Bump version to {{version}}"
tag-prefix                 = "v"
