[package]
name = "procs"
version = "0.8.11-pre"
authors = ["dalance@gmail.com"]
repository = "https://github.com/dalance/procs"
keywords = ["process"]
categories = ["command-line-utilities"]
license = "MIT"
readme = "README.md"
description = "A modern replacement for ps"
edition = "2018"

[package.metadata.release]
dev-version-ext            = "pre"
pre-release-commit-message = "Prepare to v{{version}}"
pro-release-commit-message = "Start next development iteration v{{version}}"
tag-message                = "Bump version to {{version}}"
tag-prefix                 = ""
pre-release-replacements = [
    {file="CHANGELOG.md", search="Unreleased", replace="v{{version}}"},
    {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
    {file="CHANGELOG.md", search="Change Log", replace="Change Log\n\n## [Unreleased](https://github.com/dalance/procs/compare/v{{version}}...Unreleased) - ReleaseDate"},
    {file="README.md", search = "changelog-v[0-9\\.]+", replace = "changelog-v{{version}}" },
    {file="snapcraft.yaml", search="version v[0-9\\.]+", replace="version v{{version}}"},
]

[badges]
travis-ci = { repository = "dalance/procs" }
codecov   = { repository = "dalance/procs", branch = "master", service = "github" }

[dependencies]
console       = "0.9"
chrono        = "0.4"
directories   = "2.0"
dockworker    = "0.0.15"
failure       = "0.1"
getch         = "0.2"
lazy_static   = "1.2"
libc          = "0.2"
serde         = "1.0"
serde_derive  = "1.0"
structopt     = "0.3"
toml          = "0.5"
unbytify      = "0.2"
unicode-width = "0.1"

[target.'cfg(target_os = "linux")'.dependencies]
pager         = "0.15"
process_path  = "0.1"
procfs        = "0.5.4"
quale         = "1.0"
runas         = "0.1"
users         = "0.9"

[target.'cfg(target_os = "macos")'.dependencies]
libproc       = "0.5"
errno         = "0.2"
pager         = "0.15"
process_path  = "0.1"
quale         = "1.0"
runas         = "0.1"
users         = "0.9"

[target.'cfg(target_os = "windows")'.dependencies]
winapi        = { version = "0.3", features = ["handleapi", "minwindef", "psapi", "securitybaseapi", "tlhelp32", "winbase", "winnt"] }
