name: procs
version: &version v0.8.5
summary: A modern replacement for ps written in Rust
description: |
  procs is a tool to display process information.
base: core18
license: MIT

confinement: strict

architectures:
# - build-on: amd64
# - build-on: i386
# - build-on: ppc64el
# - build-on: arm64
  - build-on: armhf

apps:
  procs:
    command: procs

parts:
  procs:
    source: https://github.com/dalance/procs.git
#   source-tag: *version
    plugin: make
    stage-packages:
      - libc6
      - libgcc1
      - libstdc++6
      - zlib1g
    build-packages:
      - curl
    override-build: |
      /build/procs/parts/procs/src/rustup.sh -y --default-toolchain none -v
      curl https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256
      ~/.cargo/bin/rustup install stable
