name: Coverage

on: [push]

jobs:
  build:

    container:
      image: xd009642/tarpaulin:latest-nightly
      options: --security-opt seccomp=unconfined

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        cargo tarpaulin -v --out Xml
        ls *.xml
    - name: Upload coverage
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
