name: Periodic

on:
  schedule:
  - cron: 0 0 * * SUN

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable, beta, nightly]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v1
    - name: Run tests
      run: cargo test
