name: Release

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        rust: [stable]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v1
    - name: Setup MUSL
      if: matrix.os == 'ubuntu-latest'
      run: |
        rustup target add x86_64-unknown-linux-musl
        apt-get -qq install musl-tools
    - name: Release linux
      if: matrix.os == 'ubuntu-latest'
      run: make release_lnx
    - name: Release macOS
      if: matrix.os == 'macOS-latest'
      run: make release_mac
    - name: Release Windows
      if: matrix.os == 'windows-latest'
      run: make release_win
